import { FileUp, RefreshCw, Trash2 } from 'lucide-react'
import { useEffect, useState } from 'react'
import api, { errorMessage } from '../api'
import { Alert, Empty, PageTitle } from '../components/Common'

export default function Materials() {
  const [subjects,setSubjects]=useState([]); const [materials,setMaterials]=useState([]); const [subjectId,setSubjectId]=useState(''); const [file,setFile]=useState(null); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [message,setMessage]=useState('')
  const load=()=>Promise.all([api.get('/subjects'),api.get('/materials')]).then(([s,m])=>{setSubjects(s.data);setMaterials(m.data);if(s.data[0]&&!subjectId)setSubjectId(String(s.data[0].id))}).catch(e=>setError(errorMessage(e))); useEffect(()=>{load()},[])
  const upload=async e=>{e.preventDefault();if(!file)return;setLoading(true);setError('');const data=new FormData();data.append('file',file);try{const r=await api.post(`/materials/upload?subject_id=${subjectId}`,data);setMessage(r.data.message);setFile(null);e.target.reset();load()}catch(err){setError(errorMessage(err))}finally{setLoading(false)}}
  const remove=async id=>{if(!confirm('Delete this material?'))return;try{await api.delete(`/materials/${id}`);load()}catch(e){setError(errorMessage(e))}}
  const rebuild=async()=>{if(!subjectId)return;setLoading(true);try{const r=await api.post(`/subjects/${subjectId}/rebuild`);setMessage(`${r.data.message}: ${r.data.chunks} chunks`)}catch(e){setError(errorMessage(e))}finally{setLoading(false)}}
  return <><PageTitle title="Material library" subtitle="PDF, PPTX, and DOCX files become searchable subject knowledge."/><Alert>{error}</Alert><Alert type="success">{message}</Alert><form onSubmit={upload} className="panel mb-6 grid gap-4 p-5 md:grid-cols-[1fr_1fr_auto] md:items-end"><label><span className="mb-2 block text-sm text-slate-300">Subject</span><select className="input" value={subjectId} onChange={e=>setSubjectId(e.target.value)} required><option value="">Choose subject</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.code} · {s.name}</option>)}</select></label><label><span className="mb-2 block text-sm text-slate-300">Study material</span><input className="input file:mr-3 file:rounded-lg file:border-0 file:bg-emerald-400/10 file:px-3 file:py-1 file:text-emerald-300" type="file" accept=".pdf,.pptx,.docx" required onChange={e=>setFile(e.target.files[0])}/></label><button className="btn-primary" disabled={loading}><FileUp size={18}/>{loading?'Processing...':'Upload'}</button></form><div className="mb-4 flex justify-end"><button className="btn-secondary" onClick={rebuild} disabled={loading||!subjectId}><RefreshCw size={17}/>Rebuild selected subject</button></div>{materials.length?<div className="grid gap-3">{materials.map(m=><div className="panel flex items-center justify-between gap-4 p-4" key={m.id}><div className="min-w-0"><p className="truncate font-medium">{m.filename}</p><p className="mt-1 text-xs text-slate-400">{m.subject_name} · {m.file_type.toUpperCase()} · {m.chunk_count} chunks</p></div><button className="btn-danger px-3" onClick={()=>remove(m.id)}><Trash2 size={16}/></button></div>)}</div>:<Empty>No materials uploaded.</Empty>}</>
}

